/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});

export const idlService = IDL.Service({
  'adoptTree' : IDL.Func([IDL.Text], [], []),
  'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getUserEvents' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'signUpForEvent' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  
  return IDL.Service({
    'adoptTree' : IDL.Func([IDL.Text], [], []),
    'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getUserEvents' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'signUpForEvent' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };